FROM 721728311103.dkr.ecr.eu-west-1.amazonaws.com/oliverstore/java:1.8.0
MAINTAINER lktslionel@gmail.com


RUN curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
RUN apt-get install -y nodejs

RUN npm install graphql -g 



